sudo: required
dist: trusty

language: python

matrix:
    include:
        - os: linux
          python: "2.7"
          env: COVERALLS=1
        - os: linux
          python: "3.4"
        - os: linux
          python: "3.5"

        - os: osx
          language: generic
          env:
            - OSXENV=2.7
        - os: osx
          language: generic
          env:
            - OSXENV=3.5

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash resources/install_osx_virtualenv.sh; fi

install:
  - export PYVER=${TRAVIS_PYTHON_VERSION:0:1}
  - if [ $COVERALLS = 1 ]; then
        pip install --upgrade coveralls;
    fi;
  - pip install lxml enum34 pyyaml

script:
  - python setup.py build
  - if [ $COVERALLS = 1 ]; then
        coverage${PYVER} run --source=odml setup.py test && coverage${PYVER} report -m;
    else
        python setup.py test;
    fi;

after_success:
- if [ $COVERALLS = 1 ]; then coveralls; fi;
